name: Main

on:
  push:
    branches: 
      - local-release

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11 for Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.12
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Init gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish packages
        run: |
          ./gradlew :kotlin-sdk:android:publish
          ./gradlew :android-sdk:android:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

